wultra/powerauth-mobile-sdk

- src/PowerAuthTests/pa2SessionTests.cpp
The issue was closed, but we still can merge that test improvements into the master.
> Issue #14: Added better test coverage for EEK-related scenarios

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java
- proj-xcode/Classes/sdk/PowerAuthSDK.m
This change addresses problems during the activation process, where the result from low level C++ code was not properly handled. The change affects IOS & Android platform
Fix #39
> Issue 39 - Wrong start activation

- src/PowerAuth/protocol/PrivateTypes.cpp
- src/PowerAuth/protocol/PrivateTypes.h
- src/PowerAuthTests/pa2ProtocolUtilsTests.cpp
This is a small change, which improves input validation for combination of signature factors.
> Improved core validation for signature factors

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/Session.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/SignedData.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/e2ee/PA2Encryptor.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/e2ee/PA2RequestResponseNonPersonalizedEncryptor.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/client/PA2Client.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/endpoints/PA2CreateActivationEndpoint.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/exceptions/ErrorResponseApiException.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java
- src/PowerAuth/jni/SessionJNI.cpp
This change also adds changes related to networking model migration to: `powerauth-restful-model:0.16.1+`
> Android: Added support for offline signatures calculation

- proj-xcode/Classes/keychain/PA2KeychainConfiguration.h
- proj-xcode/Classes/keychain/PA2KeychainConfiguration.m
- proj-xcode/Classes/networking/client/PA2ClientConfiguration.h
- proj-xcode/Classes/networking/client/PA2ClientConfiguration.m
- proj-xcode/Classes/sdk/PowerAuthSDK.h
- proj-xcode/Classes/sdk/PowerAuthSDK.m
- proj-xcode/Classes/token/PA2PrivateHttpTokenProvider.m
See issue #88 for more details
> IOS: Fix #88: PowerAuthSDK doesn't depend on shared configs.

- src/PowerAuth/jni/ECIESEncryptorJNI.cpp
- src/PowerAuth/jni/SessionJNI.cpp
> Android: Fixed #118: Correct JNI methods prototypes in module

- PowerAuth2.podspec
- proj-xcode/PowerAuthLib.xcodeproj/project.pbxproj
- scripts/templates/PowerAuth2.podspec
> IOS: Fixed #137: Forced link ObjC interfaces from "core" static library

- proj-xcode/Classes/networking/ssl/PA2ClientSslNoValidationStrategy.m
- proj-xcode/Classes/networking/ssl/PA2ClientSslValidationStrategy.h
> IOS: Fixed #139: Added nullability attributes to PA2ClientSslValidationStrategy

- include/PowerAuth/ECIES.h
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/ECIESEncryptor.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthTokenStore.java
- proj-xcode/Classes/core/PA2ECIESEncryptor.h
- proj-xcode/Classes/core/PA2ECIESEncryptor.mm
- proj-xcode/Classes/token/PA2PrivateHttpTokenProvider.m
- proj-xcode/TestClasses/PowerAuthServerSOAP/PowerAuthTestServerAPI.m
- src/PowerAuth/ECIES.cpp
- src/PowerAuth/jni/ECIESEncryptorJNI.cpp
- src/PowerAuthTests/pa2ECIESTests.cpp
This change simply adds parametrized SH1 to our low level ECIES implementation.
> Crypto3: Added support for parametrized SharedInfo1 to our ECIES implementation

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/ActivationStatus.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/ActivationStep1Param.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/ActivationStep1Result.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/ActivationStep2Param.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/ProtocolVersion.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/Session.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/SignatureFactor.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/util/otp/Otp.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/util/otp/OtpUtil.java
- src/PowerAuth/jni/ProtocolVersionJNI.cpp
- src/PowerAuth/jni/SessionJNI.cpp
- src/PowerAuth/jni/TokenCalculatorJNI.cpp
Crypto3: Android: Changed low level objects related to activation
> Crypto3: Android: Added JNI functions supporting protocol migration

- proj-android/PowerAuthLibrary/build.gradle
- proj-android/build.gradle
> Android: Raise minSdkVersion to 16

- proj-xcode/Classes/networking/client/PA2Client.m
fixed #183
Merging this PR should result in new version 0.19.4
> iOS: Fixed #183: Leaking NSURLSession

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/fingerprint/ICommitActivationWithFingerprintListener.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java
Similar to PR #196 but for legacy `0.20.x` SDK version.
> Android: Fixed #114: Improved ICommitActivationWithFingerprintListener

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/exception/PowerAuthErrorException.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/fingerprint/ICommitActivationWithFingerprintListener.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java
- Fixed missing `@PowerAuthErrorCodes` annotation
> Android: Fixed #114: Improved ICommitActivationWithFingerprintListener interface

- README.md
- docs/PowerAuth-SDK-for-Android.md
- docs/PowerAuth-SDK-for-iOS-Extensions.md
- docs/PowerAuth-SDK-for-iOS.md
- docs/PowerAuth-SDK-for-watchOS.md
- docs/Readme.md
- Added information about new E2EE encryption
- Updated custom activation
- Updated section about error handling (especially for android)
- Removed 2.0 naming from documentation
Fixes #182
> Crypto3 documentation update

- docs/PowerAuth-SDK-for-Android.md
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/response/CreateActivationResult.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/response/ICreateActivationListener.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java
- This is a backported change for V2 protocol SDK (see PR #205)
> Android: Fixed #204: Added CreateActivationResult to ICreateActivationListener (V2)

- docs/PowerAuth-SDK-for-Android.md
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/response/CreateActivationResult.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/response/ICreateActivationListener.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/impl/GetActivationStatusTask.java
This PR changes how result of the activation process is propagated to the Android app. Other changes:
- Fixed missing parameter in JavaDoc (causes a warning during the build)
> Android: Fixed #204: Added CreateActivationResult to ICreateActivationListener (V3)

- proj-xcode/Extensions/Common/Private/PA2SessionStatusDataReader.m
- proj-xcode/Extensions/IOS/PowerAuthExtensionSDK.m
- proj-xcode/Extensions/WatchOS/PowerAuthWatchSDK.m
- src/PowerAuth/protocol/PrivateTypes.cpp
Fixed compilation warnings related to PA2SessionStatusProvider protocol
> iOS: Fixed #229: Fixed activation status detection in APP extension.

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/fingerprint/FingerprintAuthenticationDialogFragment.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/fingerprint/FingerprintAuthenticationHandler.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/fingerprint/FingerprintCallback.java
Better result handling in FingerprintAuthenticationDialogFragment.
This change provides additional improvements on Issue #200
> Android: Fixed #200: Fingerprint dialog is now dismissed when canceled by the system

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/fingerprint/FingerprintAuthenticationHandler.java
Fix for `release/1.1.x` (same as for `release/0.20.x`)
> Android: Fixed #202: Workaround for crash in FingerprintManager

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/legacy/FingerprintAuthenticationHandler.java
Slightly different fix for `develop` and upcoming `release/1.2.x`
> Android: Fixed #202: Workaround for crashes in legacy FingerprintManager.

- include/PowerAuth/PublicTypes.h
- include/PowerAuth/Session.h
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/EncryptedActivationStatus.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/Session.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/model/request/ActivationStatusRequest.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/model/response/ActivationStatusResponse.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/impl/GetActivationStatusTask.java
- proj-xcode/Classes/core/PA2PrivateImpl.h
- proj-xcode/Classes/core/PA2Session.h
- proj-xcode/Classes/core/PA2Session.mm
- proj-xcode/Classes/core/PA2Types.h
- proj-xcode/Classes/core/PA2Types.mm
- proj-xcode/Classes/networking/private/request/PA2GetActivationStatusRequest.h
- proj-xcode/Classes/networking/private/request/PA2GetActivationStatusRequest.m
- proj-xcode/Classes/networking/private/response/PA2GetActivationStatusResponse.h
- proj-xcode/Classes/networking/private/response/PA2GetActivationStatusResponse.m
- proj-xcode/Classes/sdk-private/PA2GetActivationStatusTask.m
- src/PowerAuth/Session.cpp
- src/PowerAuth/jni/SessionJNI.cpp
- src/PowerAuth/protocol/Constants.cpp
- src/PowerAuth/protocol/Constants.h
- src/PowerAuth/protocol/ProtocolUtils.cpp
- src/PowerAuth/protocol/ProtocolUtils.h
- src/PowerAuthTests/pa2SessionTests.cpp
- src/PowerAuthTests/pa2SignatureCalculationTests.cpp
This PR introduces following Crypto 3.1 protocol changes:
- changes signature version to 3.1 (feature #234)
- improves activation status encryption with IV (feature #235)
Close #234
Close #235
> Crypto 3.1: Activation status & signature v3.1

- docs/Migration-from-1.1-to-1.2.md
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthentication.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricErrorDialogFragment.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricResultDispatcher.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/legacy/FingerprintAuthenticationDialogFragment.java
Also fixes problems with dialog dismissing - #255
> Android: Fix #253: Don't allow simultaneous biometric auth. requests.

- proj-xcode/Classes/keychain/PA2Keychain.h
- proj-xcode/Classes/keychain/PA2Keychain.m
- proj-xcode/Classes/sdk/PowerAuthSDK.m
PR to `release/1.2.x` and then to `develop` branch
> iOS: Fix #257: Don't allow simultaneous biometric authentication requests

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthTokenStore.java
Merge to `1.2.x` then to `develop`
> Android: Fix #262: Fixed remove token HTTP request construction (SDK 1.2+)

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthTokenStore.java
> Android: Fix #262: Fixed remove token HTTP request construction (SDK 1.1.x)

- docs/Migration-from-1.3-to-1.4.md
- docs/PowerAuth-SDK-for-Android.md
- proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/sdk/PowerAuthClientConfigurationBuilderTest.java
- proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/sdk/PowerAuthConfigurationBuilderTest.java
- proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/sdk/PowerAuthKeychainConfigurationBuilderTest.java
- proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/sdk/PowerAuthSDKBuilderTest.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthClientConfiguration.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthConfiguration.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthKeychainConfiguration.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java
- PowerAuthClientConfiguration builder refactoring _(no functional change)_
- PowerAuthConfiguration builder refactoring _(no functional change)_
- PowerAuthSDK builder refactoring _(no functional change)_
- Added Android Unit tests for configuration classes
> Android: Fix #313: PowerAuthKeychainConfiguration refactoring.

- scripts/ios-build-libraries.sh
> Apple: Fix #338: Added support for ARM64 catalyst

- docs/PowerAuth-SDK-for-Android.md
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricAuthenticator.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/legacy/FingerprintAuthenticationHandler.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/exception/PowerAuthErrorCodes.java
This PR implements FIX for #348 for `1.5.x` branch of SDK
> Android: Fix #348: Biometry lockout enhancements

- docs/PowerAuth-SDK-for-iOS.md
> Fixed #401: iOS doc error

- docs/Migration-from-1.6-to-1.7.md
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthentication.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricAuthenticator.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/IBiometricAuthenticator.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/dummy/DummyBiometricAuthenticator.java
This change improves the function that determines whether the biometric authentication is available on the system.
> Android: Fix #426: Better test whether biometric auth. is available

- scripts/ios-build-extensions.sh
- scripts/ios-build-sdk.sh
This PR fixes build warnings caused by missing `-destination` switch for xcodebuild command. I had to change order of platforms, to have "iOS" or "watchOS" platforms at first position. This is due to cleanup job that require also some destination set. Such platforms has no space characters in the destination's value so the script is more simple.
> Apple: Fix #451: Added -destination to xcodebuild command

- .github/workflows/build.yml
- scripts/android-publish-build.sh
- scripts/common-functions.sh
- scripts/deploy-build.sh
- scripts/ios-build-extensions.sh
- scripts/ios-build-sdk.sh
- scripts/test-build.sh
This PR adds build github action to test whether SDK builds properly. The PR also improves build & deploy scripts and now the verbose options is propagated across the chain of executed bash scripts. This is useful for CI builds.
> Issues/469 GitHub workflows

- proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/support/PowerAuthTestConfig.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricAuthenticator.java
This PR enhances how our biometry implementation detects that biometry is available for the signing on the device. Now we count also with the KeyGuard's state, so it's no longer possible to use biometry if device is locked, or it's not protected with unlock PIN, password or pattern.
The change also contains improvements in instrumentation tests, and now it's more straightforward to run tests agains PowerAuth Server running locally, on developer's computer.
The change is related to issues #502 and #503
> Use KeyGuard state in biometry evaluation

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/impl/GetActivationStatusTask.java
This PR fixes broken protocol upgrade on Android platform.
> Broken protocol upgrade on Android

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthTokenStore.java
This PR fixes possible token data inconsistency on Android.
> Android: Fix #539: Don't return token that is not in index.

- docs/PowerAuth-SDK-for-Android.md
- docs/PowerAuth-SDK-for-iOS.md
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/response/UserAddress.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/response/UserInfo.java
- proj-xcode/PowerAuth2/PowerAuthUserInfo.h
This PR adds documentation for feature that allows fetch information about the user.
> Getting information about user

- docs/Supported-Versions.md
- proj-android/build.gradle
> Raise minSdk to 21

- docs/Supported-Versions.md
- proj-android/build.gradle
Raise minSdk to 21 (#570)
(cherry picked from commit e2efb53f47e34f4758d46accbcf709d5eece9ea1)
> Backport #570 update to 1.7.x

- docs/PowerAuth-SDK-for-iOS.md
- proj-xcode/PowerAuth2/PowerAuthLog.h
- proj-xcode/PowerAuth2/PowerAuthLog.m
> Added Log Delegate for iOS

- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthentication.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/DialogFragmentUtil.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricAuthenticator.java
> Fix IllegalStateException when showing error dialog

- proj-android/PowerAuthLibrary/proguard-rules.pro
> Fix rules for R8 fullMode

- src/PowerAuth/PublicTypes.cpp
This PR adds support for "PATCH" HTTP method for both platforms.
> Support PATCH HTTP method

- proj-xcode/PowerAuth2.xcodeproj/project.pbxproj
- proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_IntegrationTests_iOS.xcscheme
- proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_IntegrationTests_tvOS.xcscheme
- proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_TestHostApp_iOS.xcscheme
- proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_TestHostApp_tvOS.xcscheme
- proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_iOS.xcscheme
- proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_tvOS.xcscheme
- proj-xcode/PowerAuthCore.xcodeproj/project.pbxproj
- proj-xcode/PowerAuthCore.xcodeproj/xcshareddata/xcschemes/PowerAuthCoreTests_iOS.xcscheme
- proj-xcode/PowerAuthCore.xcodeproj/xcshareddata/xcschemes/PowerAuthCoreTests_tvOS.xcscheme
- proj-xcode/PowerAuthCore.xcodeproj/xcshareddata/xcschemes/PowerAuthCore_iOS.xcscheme
- proj-xcode/PowerAuthCore.xcodeproj/xcshareddata/xcschemes/PowerAuthCore_tvOS.xcscheme
This PR fixes project update warnings related to Xcode 15.4
> Xcode 15.4 project warnings

- src/Android.mk
This PR adds support for devices with 16kB page size.
> Android: Fix #616: Support for devices with 16kB page size

- proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/tests/StandardActivationTest.java
- proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/impl/DefaultKeystoreService.java
- proj-xcode/PowerAuth2/private/PA2KeystoreService.m
- proj-xcode/PowerAuth2IntegrationTests/PowerAuthSDKDefaultTests.m
This PR fixes temporary key expiration handling on Android platform.
> Temporary key expiration
