proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/system/PA2System.java
The root detection uses couple of well-known techniques.
BusyBox detection was also added but is kept disabled for the time being
since it can cause false positives and an improvement of the detection is needed.
Fix #3
=> Add basic root detection for Android library

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/client/PA2Client.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthClientConfiguration.java
This change adds support for connections over HTTP to our PA2Client class. The feature is useful for development purposes, when the development servers typically doesn't use TLS.  
Fix #27 @syru88
=> Android: Support for connections over HTTP

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/client/PA2Client.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/exceptions/ErrorResponseApiException.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/exceptions/FailedApiException.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthClientConfiguration.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/system/PA2Log.java
This change brings better response processing to PA2Client and address following issues:
1. `NullPointerException` was raised when valid, but semantically wrong JSON was received 
2. `FileNotFound` exception was raised when 400 or 401 status code was received. Now the correct `ErrorResponseApiException` is reported
3. Now it's possible to investigate received body string later, in the user's handling routine
Also PA2Client now supports optional request & response debug logging. You can turn this feature on by calling `PA2Log.setEnabled(true)`
Fix #34, Fix #28
=> Android: HTTP response processing & debug log

proj-xcode/Classes/core/PA2ErrorConstants.h, proj-xcode/Classes/core/PA2ErrorConstants.m, proj-xcode/Classes/networking/client/PA2Client.m, proj-xcode/Classes/sdk/PowerAuthSDK.m
This is similar change to #71 but with more safe data handling. In my implementation, the response dictionary is not set directly to the error's userInfo, but under the dedicated key (`PA2ErrorInfoKey_AdditionalInfo`). That's more traditional approach on IOS when error needs to keep an additional data.
I have also fixed other possible JSON deserializer crashes on nil data.
=> IOS: Fixed #70: Hotfix for additional error info propagation when custom activation fails on the server

src/PowerAuth/Session.cpp, src/PowerAuth/protocol/PrivateTypes.cpp, src/PowerAuth/protocol/PrivateTypes.h, src/PowerAuthTests/pa2SessionTests.cpp
This change adds a support for old data format to the very low level PA code. We have still bank with clients running on very old, closed source version of the library, and thus I've decided to add that support to the core of the mobile SDK.
=> Core: Fixed #51: Added migration code from old persistent data format.

proj-xcode/Classes/sdk/PowerAuthSDK+WatchSupport.m, proj-xcode/Classes/sdk/PowerAuthToken.h, proj-xcode/Classes/token/PA2PrivateHttpTokenProvider.m, proj-xcode/Classes/token/PA2PrivateRemoteTokenProvider.h, proj-xcode/Classes/token/PA2PrivateTokenKeychainStore.m, proj-xcode/Classes/watch/PA2WCSessionManager.m, proj-xcode/Classes/watch/model/PA2WCSessionPacket_Success.m, proj-xcode/Extensions/WatchOS/private/PA2WatchRemoteTokenProvider.m, proj-xcode/Extensions/WatchOS/private/PA2WatchSynchronizationService.m
This pull request addresses several bugs which I recently found in watchOS and its counterpart IOS SDK:
- Fixed packet handling when watchOS requests IOS for token and the token doesn't exist.
- Improved error reporting when watchOS requests for token and IOS counterpart has no longer a valid activation.
- PowerAuthTokenStore on watchOS now can requst for tokens without using PowerAuthAuthentication
- If activation is removed from watchOS, then the associated tokens are also removed from keychain on watchOS
- Various small improvements, like more safe cancellable object impl., better logging, etc...
=> watchOS SDK bugfixes & Improvements

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/client/PA2Client.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/exceptions/ErrorResponseApiException.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/exceptions/FailedApiException.java
This change always adds response body and parsed `JsonObject` (if possible) to exceptions generated in our networking code.
Affected exceptions: `ErrorResponseApiException`, `FailedApiException`
=> Android: Fix #75: Always try to parse response as JSON.

proj-xcode/Classes/core/PA2ECIESEncryptor.h, proj-xcode/Classes/core/PA2Password.h, proj-xcode/Classes/core/PA2WeakArray.h
This PR has no functional changes. Just improves our SDK's interoperability with swift
Fixes #121
=> IOS: Fixed #121: Added NS_NOESCAPE annotation to objc interfaces with non-escaping closures.

proj-android/PowerAuthLibrary/build.gradle, proj-android/PowerAuthLibrary/proguard-rules.pro
Configuration is packaged into the aar library to be used when the app
is built. The configuration is minimal to allow reasonable
app obfuscation while keeping it working.
=> Android: Fixed #120: Add ProGuard config to the aar library

proj-xcode/Classes/keychain/PA2Keychain.h, proj-xcode/Classes/keychain/PA2Keychain.m
This PR brings following changes:
- `PA2SupportedBiometricAuthentication` is now deprecated and the replacement is `PA2BiometricAuthenticationType`
- added `PA2BiometricAuthenticationStatus` covering all possible states of biometry authentication
- added `struct PA2BiometricAuthenticationInfo` wrapping both "status" and "type" enumerations.
- added `PA2Keychain.biometricAuthenticationInfo` class property
Behavior of `PA2Keychain.canUseBiometricAuthentication` and `PA2Keychain. supportedBiometricAuthentication` should be the same as before.
Fixes #125
=> IOS: Provide more info about biometry and its status on the system

proj-xcode/Classes/networking/client/PA2Client.m, proj-xcode/Classes/networking/ssl/PA2ClientSslNoValidationStrategy.m, proj-xcode/Classes/networking/ssl/PA2ClientSslValidationStrategy.h
validateSslForSession is now called only for server trust challenges.
Close #131
=> IOS: Fixed #131: Changed NSURLSession configuration to ephemeral one.

include/PowerAuth/OtpUtil.h, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/util/otp/Otp.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/util/otp/OtpUtil.java, proj-xcode/Classes/core/PA2OtpUtil.h, proj-xcode/Classes/core/PA2OtpUtil.mm, src/PowerAuth/OtpUtil.cpp, src/PowerAuth/jni/OtpUtilJNI.cpp, src/PowerAuthTests/pa2OtpUtilTests.cpp
That deprecated interfaces will be removed later, when the whole activation implementation will be updated.
=> Crypto3: OtpUtil now supports V3 activation codes with CRC-16 checksum.

include/PowerAuth/PublicTypes.h, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/ActivationStatus.java, proj-xcode/Classes/core/PA2PrivateImpl.h, proj-xcode/Classes/core/PA2Types.h, proj-xcode/Classes/core/PA2Types.mm, src/PowerAuth/PublicTypes.cpp, src/PowerAuth/Session.cpp, src/PowerAuth/jni/SessionJNI.cpp
This PR is adding support for new fields to `ActivationStatus` / `PA2ActivationStatus` objects.
=> Crypto3: Core: Added activation versioning to status blob

proj-android/PowerAuthLibrary/build.gradle, proj-android/PowerAuthLibrary/gradle.properties, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java, proj-android/PowerAuthLibrary/src/test/java/io/getlime/security/powerauth/sdk/PowerAuthSDKBuilderTest.java, proj-android/PowerAuthLibrary/src/test/java/io/getlime/security/powerauth/shadow/ShadowDefaultSavePowerAuthStateListener.java, proj-android/PowerAuthLibrary/src/test/java/io/getlime/security/powerauth/shadow/ShadowSession.java
Also added unit tests based on Robolectric to test the fix.
=> Fix #164: Fix NPE in PA2Client when PowerAuthClientConfiguration not set

include/PowerAuth/PublicTypes.h, include/PowerAuth/Session.h, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/ProtocolUpgradeData.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/Session.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/impl/GetActivationStatusTask.java, proj-xcode/Classes/core/PA2PrivateImpl.h, proj-xcode/Classes/core/PA2ProtocolUpgradeData.mm, proj-xcode/Classes/core/PA2Session.h, proj-xcode/Classes/core/PA2Session.mm, proj-xcode/Classes/core/PA2Types.mm, src/PowerAuth/PublicTypes.cpp, src/PowerAuth/Session.cpp, src/PowerAuth/jni/SessionJNI.cpp, src/PowerAuth/protocol/PrivateTypes.h, src/PowerAuthTests/pa2SessionTests.cpp
This PR removes "migration" terminology from the low level C++ code and from several related high level classes in Java & ObjC. We're using "protocol upgrade" term as a right replacement. 
So, most of the changes are in the documentation, plus several methods needed to be renamed.
=> Core: Fixed #169: Removed "migration" terminology from the code base

include/PowerAuth/PublicTypes.h, proj-xcode/Classes/core/PA2Types.h, proj-xcode/Classes/networking/private/request/PA2Request.h, proj-xcode/Classes/networking/private/response/PA2Response.h, proj-xcode/Classes/networking/public/PA2AuthorizationHttpHeader.h, proj-xcode/Classes/networking/public/PA2ErrorResponse.h, proj-xcode/Classes/sdk/PowerAuthConfiguration.h, proj-xcode/Classes/sdk/PowerAuthSDK+Private.h, proj-xcode/Classes/sdk/PowerAuthSDK.h, proj-xcode/Classes/sdk/PowerAuthToken.h, proj-xcode/Classes/system/PA2System.h, proj-xcode/TestClasses/PA2CoreTestsWrapper.mm, src/PowerAuthTests/TestData/pa2/compute-derived-keys.json
The main purpose of this PR is to remove "2.0" protocol naming from the documentation comments. There's no issue attached to this. I've checked also Android sources, but that was OK, so most of changes goes to Core C++ classes and IOS ObjC.
=> Removed "2.0" protocol naming from documentation comments.

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/client/HttpClientTask.java
Since Android O, there's a new StrictMode detection `detectUntaggedSockets()`.
It requires all networking threads to have a tag so that the network traffic within the app can be identified (apps can figure out if a library is causing too much traffic).
=> Fix untagged socket detection

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/client/PA2Client.java
Similar change to #186 but for obsolete SDK compatible with V2 servers.
=> Android: Fixed untagged socket detection (V2 protocol SDK)

README.md, docs/Migration-from-0.19-to-0.20.md, docs/Migration-from-0.20-to-1.0.md, docs/Readme.md, docs/Supported-Versions.md
This PR brings a migration guides describing how to migrate from older to newer versions of SDK
Close #203
=> Documentation: Added guides for migration to 0.20 and 1.0

proj-xcode/Classes/sdk-private/PA2GetActivationStatusTask.m, src/PowerAuth/PublicTypes.cpp
IOS: Added brief documentation to PA2GetActivationStatusTask impl.
=> Core: Fixed #218: Protocol upgrade is allowed only for Active state

src/Android.mk
Fixes rare problem with `.so` dynamic library linking on some devices.
=> Android: Fixed #220: Dynamic .so lib now has GNU_HASH & HASH sections

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/fingerprint/FingerprintAuthenticationHandler.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/fingerprint/FingerprintKeystore.java
Android: Fixed #200: Fixed "IV has already been used." exception:
- This is a workaround for IV reusing in one Cipher instance. We're now using one Cipher object for FingerprintManager purposes and 2nd, ad-hoc created, for our own encryption.
Android: Fixed #199: Added catch for ProviderException
=> Crashes in Android Fingerprint dialog

proj-xcode/Classes/keychain/PA2Keychain.m, scripts/ios-build-libraries.sh
This PR also fixes build problem, introduced in #241. The `util` folder is no longer in the project tree.
=> iOS: Fixed #248: Keychain workaround for iOS 13 simulator

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthentication.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricAuthenticator.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricHelper.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricResultDispatcher.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/legacy/FingerprintAuthenticator.java
This PR adds ability to display error dialog even when the biometric authentication succeeds, but fails to encrypt the biometric key. I've also added a lot of error logs to the code, to help developers determine what's the problem with the biometry.
=> Android: Fix #259: Handle errors after biometric authentication success

proj-xcode/Classes/networking/private/client/PA2AsyncOperation.m, proj-xcode/PowerAuthLib.xcodeproj/project.pbxproj, proj-xcode/TestClasses/PA2AsyncOperationTests.m, proj-xcode/TestClasses/PowerAuthServerSOAP/AsyncHelper.m
- Fixed broken `PA2AsyncOperation` cancelation.
- Added unit tests for `PA2AsyncOperation`
- Fixed limited delay in `AsyncHelper` test helper.
=> Broken cancel in PA2AsyncOperation

src/PowerAuth/Session.cpp, src/PowerAuth/protocol/ProtocolUtils.cpp, src/PowerAuth/protocol/ProtocolUtils.h
This PR fixes both issues related to the protocol upgrade from V2 to V3.1. Ticket #302, #303
=> Core: Fix #303: V2 signature calculation before protocol upgrade

proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/keychain/KeychainFactoryTest.java, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/keychain/impl/BaseKeychainTest.java, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/keychain/impl/EncryptedKeychainTest.java, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/keychain/impl/KeychainMigrationTest.java, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/keychain/impl/LegacyKeychainTest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/impl/EncryptedKeychain.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/impl/LegacyKeychain.java
This PR adds unit tests for `Keychain` and `KeychainFactory` interfaces.
The unit tests revealed that it's impossible to distinguish between previously stored empty string and stored empty array of bytes. Both situations leads to empty string to be set to the keychain. Due to this reason, the import to `EncryptedKeychain` removes all strings from the keychain. I think this is the most compatible approach, because previous `PA2Keychain` interface had no data nullability specified, so we had always to handle empty strings or data.
=> Android Keychain unit tests

include/PowerAuth/Session.h, proj-xcode/PowerAuthLib.xcodeproj/xcshareddata/xcschemes/PA2_Release.xcscheme, proj-xcode/TestClasses/PowerAuthSDKTests.m, src/PowerAuth/Session.cpp, src/PowerAuthTests/pa2SessionTests.cpp
- iOS Fixed tests running in "PA2_Release"
=> ActivationId and ActivationFingerprint is available after key-exchange

README.md, docs/Migration-from-1.3-to-1.4.md, docs/Migration-from-1.4-to-1.5.md, docs/PowerAuth-SDK-for-Android.md, docs/Readme.md, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/sdk/PowerAuthKeychainConfigurationBuilderTest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthentication.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthenticationRequest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricKeyData.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/IAddBiometryFactorListener.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/IBiometricAuthenticationCallback.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/IBiometricKeyEncryptor.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/IBiometricKeystore.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/ICommitActivationWithBiometryListener.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricAuthenticator.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricHelper.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricKeyEncryptorAes.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricKeyEncryptorRsa.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricKeystore.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricResultDispatcher.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/PrivateRequestData.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/dummy/DummyBiometricKeystore.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/legacy/FingerprintAuthenticator.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/exception/PowerAuthErrorException.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthKeychainConfiguration.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/impl/DummyCancelable.java
This PR adds support for biometric factor protected by asymmetric RSA key-pair, stored in Android keystore.
=> Android: Fix #332: Support for asymmetric biometric key

docs/PowerAuth-SDK-for-iOS.md, proj-xcode/Classes/core/PA2ErrorConstants.h, proj-xcode/Classes/core/PA2ErrorConstants.m, proj-xcode/Classes/core/PA2PrivateMacros.m, proj-xcode/Classes/sdk/PowerAuthAuthentication.h, proj-xcode/Classes/sdk/PowerAuthAuthentication.m, proj-xcode/Classes/sdk/PowerAuthSDK.h, proj-xcode/Classes/sdk/PowerAuthSDK.m
* Added missing biometry lock in unlockBiometryKeysWithPrompt method
* Added PowerAuthAuthentication static method to make possession+biometry with prompt
* Added new PA2ErrorCodeBiometryFailed error constant
* iOS: Core: Fix #376: Add text description to NSErrors
This is backport from develop to 1.5.x branch
=> iOS: Fix #367: Prepare PowerAuthAuthentication for possession+biometry in advance (1.5.x)

proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/core/CryptoUtilsTest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/CryptoUtils.java, src/PowerAuth/jni/CryptoUtilsJNI.cpp
Enhances Android's CryptoUtils class with the following functionality:
- Compute HMAC_SHA_256
- Generate random bytes
Note that this PR adds the functionality to Android platform only. The similar implementation for Apple will be delivered with #373 / PR #385
=> Android: Fix #355: CryptoUtils enhanced with HMAC and random generator

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricKeyEncryptorAes.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricKeyEncryptorRsa.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/SymmetricKeyProvider.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/keychain/impl/AesGcmImpl.java
This fix catch `ProviderException` at various code paths, related to Android KeyStore based encryption & decryption.
=> Android: Fix #353: Catch ProviderException

proj-xcode/PowerAuth2/PowerAuthSDK.m
This is a fix for #419 back-ported to 1.6.x release branch.
=> Apple: Fix #419: Reset pending activation after failed ECIES.

proj-xcode/PowerAuth2/PowerAuthKeychain.m, proj-xcode/PowerAuth2ForExtensions/PowerAuthKeychain.m, proj-xcode/PowerAuth2ForWatch/PowerAuthKeychain.m
This is a fix for #421 backported to 1.6.x release branch.
=> Apple: Fix #421: Ignore access group config for simulator keychain (1.6.x branch)

docs/Migration-from-1.6-to-1.7.md, docs/PowerAuth-SDK-for-Android.md, docs/PowerAuth-SDK-for-iOS.md, proj-android/PowerAuthLibrary/build.gradle, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/client/HttpClientTask.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthClientConfiguration.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/system/PowerAuthSystem.java, proj-xcode/PowerAuth2/PowerAuthClientConfiguration.h, proj-xcode/PowerAuth2/PowerAuthClientConfiguration.m, proj-xcode/PowerAuth2/PowerAuthMacros.h, proj-xcode/PowerAuth2/PowerAuthSystem.h, proj-xcode/PowerAuth2/PowerAuthSystem.m, proj-xcode/PowerAuth2/private/PA2HttpClient.m, proj-xcode/PowerAuth2ForExtensions/PowerAuthMacros.h, proj-xcode/PowerAuth2ForExtensions/PowerAuthSystem.h, proj-xcode/PowerAuth2ForExtensions/PowerAuthSystem.m, proj-xcode/PowerAuth2ForWatch/PowerAuthMacros.h, proj-xcode/PowerAuth2ForWatch/PowerAuthSystem.h, proj-xcode/PowerAuth2ForWatch/PowerAuthSystem.m, proj-xcode/PowerAuth2IntegrationTests/PowerAuthServerSOAP/AsyncHelper.m
This PR adds support for application provided User-Agent added to all HTTP requests initiated from the library. The change also defines a default User-Agent string provided by PowerAuth SDK itself, if client configuration is not altered.
=> Add support for custom User-Agent

docs/PowerAuth-SDK-for-Android.md, docs/PowerAuth-SDK-for-iOS.md
Added note that inform developer about behavior when biometry is locked out.
=> Documentation: Fix #425: Added note about SDK behavior when biometry is locked out.

docs/Migration-from-1.6-to-1.7.md, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/client/HttpClientTask.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/client/JsonSerialization.java
This PR fixes issue where `IOException` was reported back to application from networking stack used by SDK internally. Now this type of exception is wrapped into `PowerAuthErrorException` with `NETWORK_ERROR` error code.
On top of that, change Fixes deprecated API usage in `JsonSerialization` class.
=> Android: Fix #406: IOException wrapped into PowerAuthErrorException

proj-android/PowerAuthLibrary/android-release-aar.gradle, proj-android/PowerAuthLibrary/build.gradle, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/support/client/HttpRestClient.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/impl/GetActivationStatusTask.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/system/PowerAuthSystem.java
This PR fixes issue in gradle when library is publishing to local or remote maven. On top of that, it fixes warnings with deprecated API usage (JsonParser)
=> Android: Fix #455: Fixed javadoc generator parameters

docs/Migration-from-1.6-to-1.7.md, include/PowerAuth/Password.h, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/core/PasswordTest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/Password.java, proj-xcode/PowerAuthCore.xcodeproj/project.pbxproj, proj-xcode/PowerAuthCore/PowerAuthCorePassword.h, proj-xcode/PowerAuthCore/PowerAuthCorePassword.mm, proj-xcode/PowerAuthCoreTests/PowerAuthCorePasswordTests.m, src/PowerAuth/Password.cpp, src/PowerAuth/jni/PasswordJNI.cpp, src/PowerAuthTests/pa2PasswordTests.cpp
This PR adds simple passphrase obfuscation to our "core" password objects . The method of obfuscation is based on a simple XOR function, with using random 16 bytes as cyclic key.
The change also contains the following modifications:
- Added high level tests for `Password` (android) & `PowerAuthCorePassword` (ios, tvos)
- Removed CC7_CHECK from `Password.cpp` implementation. This has no effect on functionality, but it required due to problematic unit testing on iOS. 
- Added `Password.validatePasswordComplexity` function to Android impl.
- Changed `PowerAuthCorePassword.validatePasswordComplexity()` return value.
=> Core: Fix #499: Obfuscate password stored in memory

docs/PowerAuth-SDK-for-iOS.md, proj-xcode/PowerAuth2/PowerAuthKeychain.m, proj-xcode/PowerAuth2/PowerAuthKeychainConfiguration.h, proj-xcode/PowerAuth2/PowerAuthKeychainConfiguration.m, proj-xcode/PowerAuth2/PowerAuthSDK.h, proj-xcode/PowerAuth2/PowerAuthSDK.m, proj-xcode/PowerAuth2ForExtensions/PowerAuthKeychain.m, proj-xcode/PowerAuth2ForExtensions/PowerAuthKeychainConfiguration.h, proj-xcode/PowerAuth2ForExtensions/PowerAuthKeychainConfiguration.m, proj-xcode/PowerAuth2ForWatch/PowerAuthKeychain.m, proj-xcode/PowerAuth2ForWatch/PowerAuthKeychainConfiguration.h, proj-xcode/PowerAuth2ForWatch/PowerAuthKeychainConfiguration.m, proj-xcode/PowerAuth2IntegrationTests/PowerAuthSDKDefaultTests.m
This PR adds various improvements to LAContext usage in SDK:
- LAContext is automatically invalidated after use
- Fixed naming of PowerAuthSDK methods using LAContext
- Improved error reporting when SDK fails to fetch biometry key from the keychain
- Added "Biometry troubleshooting" section to documentation, explaining in more detail possible failures with biometry.
=> LAContext improvements

proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/tests/ActivationHelper.java, src/PowerAuth/jni/SessionJNI.cpp, src/PowerAuthTests/pa2OtpUtilTests.cpp
This PR fixes an issue when Activation Id and Activation Fingerprint is not available after key-exchange on Android platform. 
On top of that it fixes missing comma in C++ test class. The result of the test is not affected, but test data now contains originally intended test vectors.
=> Android: Reveal activationId & fingerprint in pending activation

proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/tests/StandardActivationTest.java, proj-xcode/PowerAuth2/PowerAuthSDK.m, proj-xcode/PowerAuth2IntegrationTests/PowerAuthSDKDefaultTests.m
Don't reset activation in createActivation() if there's already some existing or pending activation.
=> iOS: Fix #488: Don't reset activation in createActivation() call

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/Session.java
Fixes crash when null is provided to `Session.prepareKeyValueDictionaryForDataSigning()`
=> Fix #490: Allow null in Session.prepareKeyValueDictionaryForDataSigning()

proj-xcode/PowerAuth2/PowerAuthKeychain.m, proj-xcode/PowerAuth2/PowerAuthSDK+WatchSupport.m, proj-xcode/PowerAuth2/PowerAuthSDK.m, proj-xcode/PowerAuth2/PowerAuthToken+WatchSupport.m, proj-xcode/PowerAuth2/PowerAuthWCSessionManager.m, proj-xcode/PowerAuth2ForExtensions/PowerAuthKeychain.m, proj-xcode/PowerAuth2ForWatch/PowerAuthKeychain.m, proj-xcode/PowerAuth2ForWatch/PowerAuthWCSessionManager.m, proj-xcode/PowerAuth2IntegrationTests/PowerAuthSDKDefaultTests.m
This PR cleanups iOS, tvOS & watchOS codebase from the already ineffective platform checks. 
Just for note, currently we support iOS 11+, tvOS 11+ and watchOS 4+
=> Apple: Fix #492: Targeting code to iOS 11+

proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/tests/ActivationHelper.java, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/tests/StandardActivationTest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java
This PR fixes internal `PowerAuthAuthentication` object construction in convenient methods for activation commit.
=> Fix #485: PowerAuthAuthentication internal use for activation commit

docs/Migration-from-1.6-to-1.7.md, docs/PowerAuth-SDK-for-iOS.md, proj-android/build.gradle, proj-xcode/PowerAuth2/PowerAuthErrorConstants.h, proj-xcode/PowerAuth2/PowerAuthErrorConstants.m, proj-xcode/PowerAuth2/PowerAuthSDK.h, proj-xcode/PowerAuth2/PowerAuthSDK.m, proj-xcode/PowerAuth2ForExtensions/PowerAuthErrorConstants.m, proj-xcode/PowerAuth2ForWatch/PowerAuthErrorConstants.m, proj-xcode/PowerAuth2IntegrationTests/PowerAuthSDKDefaultTests.m
This PR fixes bug #495 and enhances `authenticateUsingBiometry()` function to properly handle all possible failures that can happen during the biometric authentication.
=> Improved authenticateUsingBiometry() on iOS

proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/core/PasswordTest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/Password.java, proj-xcode/PowerAuthCore/PowerAuthCorePassword.h, proj-xcode/PowerAuthCore/PowerAuthCorePassword.mm, proj-xcode/PowerAuthCoreTests/PowerAuthCorePasswordTests.m, src/PowerAuth/jni/PasswordJNI.cpp
This PR adds methods for copying core passwords into immutable objects. See associated ticket #500 for more details.
=> Copy Core Password

PowerAuth2ForExtensions.podspec, PowerAuthCore.podspec, docs/PowerAuth-SDK-for-iOS.md, scripts/ios-build-extensions.sh, scripts/ios-build-sdk.sh, scripts/templates/PowerAuth2ForExtensions.podspec, scripts/templates/PowerAuthCore.podspec, scripts/test-build.sh
This PR changes the default behavior for tvOS platform when library is integrated with CocoaPods. The tvOS SDK is no longer enforced and if it's not installed on the development machine, then the platform is not included in the final `xcframework`.
=> Apple: Fix #510: tvOS SDK is no longer required

proj-xcode/PowerAuth2/PowerAuthUserInfo.h
This PR makes `PowerAuthUserInfo` and `PowerAuthUserAddress` object constructors public.
=> Public constructor for PowerAuthUserInfo and PowerAuthUserAddress

proj-android/PowerAuthLibrary/proguard-rules.pro
Keep whole classes instead of class members only in networking.model.**
=> Android: Fix #526: Proguard rules update

docs/PowerAuth-SDK-for-Android.md, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/tests/TestClass.kt, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthentication.java
If device says that biometric authentication is possible but the type of biometry cannot be determined, then report `BiometryType.GENERIC`. This may happen in two situations:
- Device has a brand new type of sensor not supported in our SDK
- Device is broken, because failed to declare supported set of features, such as `PackageManager.FEATURE_FINGERPRINT`
=> Report BiometryType.GENERIC on broken or new devices

.gitignore, docs/PowerAuth-SDK-for-Android.md, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthentication.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricErrorInfo.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/IAuthenticateWithBiometricsListener.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/IAuthenticateWithBiometryListener.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/ICommitActivationWithBiometryListener.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/IPersistActivationWithBiometricsListener.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricAuthenticator.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/PrivateRequestData.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/exception/PowerAuthErrorCodes.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/exception/PowerAuthErrorException.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/response/IGenerateTokenHeaderListener.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/response/IServerStatusListener.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthConfiguration.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/impl/KVHelper.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/impl/VaultUnlockReason.java, proj-android/build.gradle
This PR adds option to disable error dialog presented from PowerAuth SDK after biometry fail. If the error dialog is disabled, then application can detect whether failure should be displayed to the user with using new `BiometricErrorInfo` enumeration, associated to `PowerAuthErrorException`.
Other changes:
- Simplified `PowerAuthSDK.authenticateWithBiometry()`. The authenticate methods now use new `IAuthenticateWithBiometryListener` that return `PowerAuthAuthentication` in success.
- Added support for missing `BIOMETRY_NOT_ENROLLED` error code (unification with iOS)
Note that documentation doesn't contain new steps for migration to 1.8. This is covered in separate PR #550
=> Android: Option to disable error dialog after failed biometry

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricKeyData.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthAuthentication.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java
This PR allows manual destruction of PowerAuthAuthentication object on Android. On top of that, we make sure that biometric key and other sensitive keys are also destroyed.
=> Destroy authentication object

docs/Migration-from-1.7-to-1.8.md, docs/PowerAuth-SDK-for-Android.md, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthentication.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricErrorInfo.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricAuthenticator.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricHelper.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java
This PR changes how new `BiometricErrorInfo` is defined. Now it is a class instead of enumeration. This change allows us to embed more information than simple hint about the dialog presentation.
Other changes:
- Fixed mapping from `BiometricStatus.NOT_ENROLLED` to `PowerAuthErrorCodes.BIOMETRY_NOT_ENROLLED`
- `BiometricAuthentication.getBiometricDialogResources()` is now static (as intended)
=> BiometricErrorInfo now contains localized reason of failure

proj-xcode/PowerAuth2/private/PA2TimeSynchronizationService.h
This change is important for CocoaPods integration. Import of particular header doesn't work in CocoaPods, so we have to use module import.
=> Apple: Import PowerAuthCore as module in private header

docs/PowerAuth-SDK-for-iOS.md
- Fixed #574 (stop using `sharedInstance` in the documentation)
- this will align the documentation with the Android
- we should not encourage our users to use `sharedInstance` anyway, because it can cause trouble later on when switching instances (end-user accounts) and is a bad pattern for modern DependencyInjection systems
- it's a confusing point for our customers
- Fixed #573: customObject fix
=> iOS documentation fixes

docs/PowerAuth-SDK-for-Android.md, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/system/PowerAuthLog.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/system/PowerAuthLogListener.java
Adding a log listener to be able to tap into logs and log them into file/online system.
More explanation in the issue: #583
=> Added log listener

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/client/HttpClientTask.java
This PR fixes crash in android's HttpClientTask logging when failure occurs before the connection is established.
=> Android: Fix #579: Crash in HttpClientTask logging

proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/core/ActivationStatus.java
This PR fixes missing `@Nullable` annotation in `ActivationStatus.getCustomObject()`.
=> Nullable annotation in ActivationStatus.getCustomObject()

proj-xcode/PowerAuth2/PowerAuthLog.h, scripts/config-apple.sh
This PR fixes warnings introduced in Xcode 15.3 and removes support for `arm64e` architecture
=> Xcode 15.x warnings

docs/Migration-from-1.8-to-1.9.md, docs/PowerAuth-SDK-for-Android.md, docs/PowerAuth-SDK-for-iOS.md, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/sdk/PowerAuthActivationBuilderTest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/networking/model/entity/ActivationType.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthActivation.java, proj-xcode/PowerAuth2/PowerAuthActivation.h, proj-xcode/PowerAuth2/PowerAuthActivation.m, proj-xcode/PowerAuth2Tests/PowerAuthActivationTests.m
This PR adds support for new OIDC activation flow. Other changes:
- There's still "CUSTOM" activation type defined for custom activations.
-  All `PowerAuthActivation` object constructors are now available with no `activationName` parameter. The new recommended way to alter activation name is to use a new builder method `setActivationName()` or `with(activationName:)`. To avoid conflicts, I'll reflect this change in documentation in separate PR #618
=> Support for OIDC activation

docs/Supported-Versions.md, proj-xcode/PowerAuth2.xcodeproj/project.pbxproj, proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_IntegrationTests_iOS.xcscheme, proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_IntegrationTests_tvOS.xcscheme, proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_TestHostApp_iOS.xcscheme, proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_TestHostApp_tvOS.xcscheme, proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_iOS.xcscheme, proj-xcode/PowerAuth2.xcodeproj/xcshareddata/xcschemes/PowerAuth2_tvOS.xcscheme, proj-xcode/PowerAuthCore.xcodeproj/project.pbxproj, proj-xcode/PowerAuthCore.xcodeproj/xcshareddata/xcschemes/PowerAuthCoreTests_iOS.xcscheme, proj-xcode/PowerAuthCore.xcodeproj/xcshareddata/xcschemes/PowerAuthCoreTests_tvOS.xcscheme, proj-xcode/PowerAuthCore.xcodeproj/xcshareddata/xcschemes/PowerAuthCore_iOS.xcscheme, proj-xcode/PowerAuthCore.xcodeproj/xcshareddata/xcschemes/PowerAuthCore_tvOS.xcscheme
This PR updates Xcode project files to get rid of warnings introduced in Xcode16. On top of that it contains the following changes:
- macOS minimum target is now 11.0 (affects macOS Catalyst version of the library)
- cc7 submodule update
- Fixed Xcode16 warnings
- OpenSSL 1.1.1w
=> Fixed warnings in Xcode16

docs/Migration-from-1.6-to-1.7.md, docs/Migration-from-1.7-to-1.8.md, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/support/PowerAuthTestHelper.java, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/tests/ActivationHelper.java, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/tests/StandardActivationTest.java, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/sdk/PowerAuthKeychainConfigurationBuilderTest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthentication.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthenticationRequest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/IBiometricKeystore.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricKeystore.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/DefaultBiometricKeyEncryptorProvider.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/dummy/DummyBiometricKeystore.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthKeychainConfiguration.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/impl/BiometricDataMapper.java
This PR modifies how the `PowerAuthSDK` class on Android internally stores biometry-related encryption keys. In previous versions, the key was shared between multiple `PowerAuthSDK` instances. Now, the shared key is only used if the activation has already configured a biometric factor. Once the factor using the shared key is removed, or the entire activation is removed, a per-instance key will be created during the next biometric setup.
This backward compatibility feature can be disabled in the `PowerAuthKeychainConfiguration` if required by the application. For instance, if the application uses multiple instances of `PowerAuthSDK`, it is important to disable this feature to ensure the shared key is immediately forgotten.
=> Store biometry key for each PowerAuthSDK instance (1.8.x)

docs/Migration-from-1.6-to-1.7.md, docs/Migration-from-1.7-to-1.8.md, docs/Migration-from-1.8-to-1.9.md, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/support/PowerAuthTestHelper.java, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/tests/ActivationHelper.java, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/tests/StandardActivationTest.java, proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/sdk/PowerAuthKeychainConfigurationBuilderTest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthentication.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/BiometricAuthenticationRequest.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/IBiometricKeystore.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/BiometricKeystore.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/DefaultBiometricKeyEncryptorProvider.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/biometry/impl/dummy/DummyBiometricKeystore.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthKeychainConfiguration.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/PowerAuthSDK.java, proj-android/PowerAuthLibrary/src/main/java/io/getlime/security/powerauth/sdk/impl/BiometricDataMapper.java
This PR modifies how the `PowerAuthSDK` class on Android internally stores biometry-related encryption keys. In previous versions, the key was shared between multiple `PowerAuthSDK` instances. Now, the shared key is only used if the activation has already configured a biometric factor. Once the factor using the shared key is removed, or the entire activation is removed, a per-instance key will be created during the next biometric setup.
This backward compatibility feature can be disabled in the `PowerAuthKeychainConfiguration` if required by the application. For instance, if the application uses multiple instances of `PowerAuthSDK`, it is important to disable this feature to ensure the shared key is immediately forgotten.
This PR is also back-ported to releases 1.7.x and 1.8.x (#626, …
=> Store biometry key for each PowerAuthSDK instance

proj-android/PowerAuthLibrary/src/androidTest/java/io/getlime/security/powerauth/integration/tests/StandardActivationTest.java, proj-xcode/PowerAuth2/PowerAuthSDK.m, proj-xcode/PowerAuth2IntegrationTests/PowerAuthSDKDefaultTests.m
This PR fixes ECIES encryptor creation for application purposes, when `PowerAuthSDK` object is freshly instantiated.
=> Fixed public ECIES encryptor construction
